# Generated by Django 3.2.3 on 2021-06-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='image',
            field=models.ImageField(default='example.jpg', upload_to=''),
        ),
    ]
